# Generated by Django 3.2 on 2025-03-28 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('ponto_referencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.IntegerField(default=1)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.address')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('telefone_whatsapp', models.CharField(max_length=20)),
                ('vinculo', models.CharField(choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('tutor', 'Tutor'), ('responsavel_legal', 'Responsável Legal'), ('avo', 'Avô/Avó'), ('outro', 'Outro')], max_length=50)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=50)),
                ('orgao_emissor', models.CharField(max_length=100)),
                ('estado_emissao', models.CharField(max_length=2)),
                ('cartao_sus', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('telefone_whatsapp', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=20)),
                ('pcd', models.BooleanField(default=False)),
                ('bolsa_familia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_sus', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('laudo_pcd', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('comprovante_residencia', models.FileField(upload_to='documents/')),
                ('historico_escolar', models.FileField(upload_to='documents/')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matricula.enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.responsibleprofile'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.schoolunit'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matricula.studentprofile'),
        ),
    ]
